config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
=======

>>>>>>> ViewController
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'}, 
  	:controllers => { :omniauth_callbacks => "omniauth_callbacks"}

  
  get 'pages/about'
  get 'myprojects' => 'project#list'
  post '/free' => 'charges#free'

  root 'project#index'

  resources :project do 
  	resources :task, only: [:show]
  end

  resources :project do 
    resources :reviews, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
end

app/models/project.rb
class Project < ApplicationRecord
	extend FriendlyId
	friendly_id :name, use: [:slugged, :finders]
	has_many :tasks

	has_many :subscriptions
	has_many :users, through: :subscriptions

	has_many :reviews

	validates :name, presence: true, length: {maximum:50}
	validates :content, presence: true, length: {maximum:5000}
	validates :price, presence: true, numericality: { only_integer: true }

	has_attached_file :image, styles: { medium: "680x300>", thumb: "170x75>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


   def shortname
    name.length > 25? name[0..25] + "..." : name 
  end

  def average_rate 
  	reviews.blank? ? 0 : reviews.average(:star).round(2)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/subject.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/task.rb
class Task < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: [:slugged, :finders]
	belongs_to :project
	validates :title, presence: true, length: {maximum:50}
	validates :video, presence: true
	#validates :tag, presence: true
	validates :project, presence: true

	def next
		project.tasks.where("tag > ? AND header = ?", tag, false).order(:tag).first 
	end


	def previous
		project.tasks.where("tag < ? AND header = ?", tag, false).order(:tag).last 
	end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  has_many :subscriptions
  has_many :projects, through: :subscriptions
  has_many :reviews

  validates :name, presence: true, length: {maximum:25}
  after_create :send_notification
  def send_notification
    MyMailer.new_user(self).deliver
  end


  def self.find_for_google_oauth2(access_token, signed_in_resourse = nil)
  	data = access_token.info
  	user = User.where(:provider => access_token.provider, :uid => access_token.uid).first

  	if user
  		return user
  	else
  		registered_user = User.where(:email => access_token.email).first
  		if registered_user
  			return registered_user
  		else
  			user = User.create(
  				name: data["name"],
          images: data["image"],
  				provider: access_token.provider,
  				email: data["email"],
  				uid: access_token.uid,
  				password: Devise.friendly_token[0,20]
  				)
  		end
  	end
  end


  def self.find_for_facebook_oauth(access_token, signed_in_resourse = nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid).first

    if user
      return user
    else
      registered_user = User.where(:email => data.email).first
      if registered_user
        return registered_user
      else
        user = User.create(
          name: access_token.info.name,
          images: access_token.info.image,
          provider: access_token.provider,
          email: access_token.info.email,
          uid: access_token.uid,
          password: Devise.friendly_token[0,20]
          )
      end
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ActionController::Base
	before_action :authenticate_user!
	def free
		project = Project.find(params[:project_id])
		current_user.subscriptions.create(project: project)

		redirect_to project
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  before_action :authenticate_user!, only: [:list ]
  def index
  	@project = Project.all
  end

  def show
  	@project = Project.find(params[:id])
  	@tasks = @project.tasks.order(:tag)

  	@joined = false

  	if !current_user.nil? && !current_user.projects.nil?
  		@joined = current_user.projects.include?(@project)
  	end

  	@user = @project.users.order('created_at desc').first(10)

    @review = Review.new 
    @reviews = @project.reviews
    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
   end

  def list 
    if !current_user.nil?
      @project = current_user.projects
    end    
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def create 
		@review = Review.create(review_params)
		project = @review.project

		

		redirect_to project
	end

	def destroy	
		@review = Review.find(params[:id])
		project = @review.project
		@review.destroy

		redirect_to project
	end

	private 
	def review_params
		params.require(:review).permit(:star, :comment, :project_id, :user_id)
	end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController

	before_action :authenticate_user!


  def show
  	project = Project.find(params[:project_id])
  	@tasks = project.tasks.order(:tag)

  	joined = false

  	if !current_user.nil? && !current_user.projects.nil?
  		joined = current_user.projects.include?(project)
  	end

  	if joined
  		@task = @tasks.find(params[:id])
  	else 
  		flash[:notice] = "no permission to this"
  		redirect_to project
  	end

    @next_task = @task.next 
    @prev_task = @task.previous


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		gravatar_id = Digest::MD5::hexdigest(user.email).downcase
		if user.images
			user.images
		else
		"https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identicon&s=40"
		end
	end

	def timeago(time, options={} )		
		options[:class] ||= "timeago"
		content_tag(
			:time,
			time.to_s,
			options.merge(datetime: time.getutc.iso8601)
			) if time 
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>

    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= yield :head %>


    <script src="//load.sumome.com/" data-sumo-site-id="353da4e801ab4d5db2921ff684186fbe43328f2af167d743f0b4c309bb87dbd0" async="async"></script>

  </head>

  <body>
  
  <%= render partial: "shared/header"%>
  <%= render partial: "shared/message"%>
	<main class="container">
		<%= yield %>
	</main>
  <%= render partial: "shared/footer"%>
    
            
  </body>
</html>


<script type="text/javascript">
  $(".button-collapse").sideNav();
  $(".dropdown-button").dropdown();
        
</script>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>

<% end %>

app/views/shared/_footer.html.erb
 <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>

app/views/shared/_header.html.erb
	<header>
  		<ul id="dropdown1" class="dropdown-content">
		  <li><%= link_to "My Profile", edit_user_registration_path %></li>
		  <li><%= link_to "My Courses", myprojects_path%></li>
		  <li class="divider"></li>
		  <li><%= link_to "Log out",destroy_user_session_path, method: :delete %></li>
		</ul>

		<ul id="dropdown2" class="dropdown-content">
		  <li><%= link_to "My Profile", edit_user_registration_path %></li>
		  <li><%= link_to "My Courses", myprojects_path%></li>
		  <li class="divider"></li>
		  <li><%= link_to "Log out",destroy_user_session_path, method: :delete %></li>
		</ul>



  		<nav>
  			<div class="container">  
			    <div class="nav-wrapper">
			      <a href="#!" class="brand-logo">Alice Education</a>
			      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
			      <ul class="right hide-on-med-and-down">
			        	 <li> <%= link_to "Projects", root_path%></li>
			        <%if(!user_signed_in?)%>
				        <li><%= link_to "Sign up", new_user_registration_path %></li>
				        <li><%= link_to "Log in", new_user_session_path %></li>
				    <% else %>

			        	<li>			
			        		<a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown1">
			        		<%=  image_tag avatar_url(current_user), class:"circle responsive-img image-size" %> &nbsp	
			        		<%= current_user.name %><i class="material-icons right"></i></a>
			        	</li>
			        <%end%>
			        
			      </ul>
			      <ul class="side-nav" id="mobile-demo">
			        <li><a href="#">Courses</a></li>
			        <%if(!user_signed_in?)%>
				        <li><%= link_to "Sign up", new_user_registration_path %></li>
				        <li><%= link_to "Log in", new_user_session_path %></li>
				    <% else %>
			        	<li>
			        		<a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown2">
			        			<%=  image_tag avatar_url(current_user), class:"circle responsive-img" %> &nbsp	
			        			<%= current_user.name %><i class="material-icons right"></i>
			        		</a>
			        	</li>
			        <%end%>
			      </ul>
			 	</div>
			 </div>
  		</nav>	
  	</header>

app/views/shared/_message.html.erb
<% unless flash.empty?%>
	<script>
		<% flash.each do |f|%>
		<% type=f[0].to_s.gsub('alert','error').gsub('notice','info') %>
			toastr['<%= type %>']('<%= f[1]%>')
		<%end%>
	</script>
<% end %>